author: elbee-cyber
name: Dylan Knoff

title: FaultPoint Blog
description: >- # this means to ignore newlines until "baseurl:"
  I'm Dylan, a undergraduate CS student at George Mason and independent security researcher. This blog is where I post articles relating to CTFs, personal projects, hacking and whatever else is appropiate. <a href="/blog.html">Go to blog</a>

email: dontopenthis@protonmail.com

# social links
twitter_username: elbee_ez
github_username:  elbee-cyber
# rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: dylan.kno
linkedin_username: dylan-knoff
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# baseurl: http://127.0.0.1:4000
header_pages:
  - index.md
  - blog.md

# Config section the home


# Build settings
markdown: kramdown

jekyll-theme-experiment:
  about:
    avatar :https://64.media.tumblr.com/3261894a2d13729b5be3a6dd1797ad3c/tumblr_nzmlu6EAT11spqzn1o1_500.gif



exclude:
  - Gemfile
  - Gemfile.lock
